### ISSUE TITLE
怎么看本地eureka里注册的实例啊？

### ISSUE THREAD

**Issue by jyy1990** [SpringCloud/Moss#17]
我给布到本地了，之前也没用过springboot admin。我在左上角注册中心切到内网服务器上的eureka了，这个eureka上面现在注册了一个我配置成mossClient的微服务了,但是为什么这个微服务没有在moss web服务端的页面有任何展示或者反馈。是我理解不对吗,我认为切换到指定注册中心之后，该注册中心上所有配置成mossClient的微服务都能展示在mossWeb平台上。
![image](https://user-images.githubusercontent.com/35125132/56718645-bc528200-6771-11e9-9ab2-702f46e9c765.png)

**Comment by SoftwareKing** [comment]
@jyy1990 注册中心管理添加注册中心成功没？加我微信Software_King进交流群

**Comment by jyy1990** [comment]
@SoftwareKing  添加了注册中心了
![image](https://user-images.githubusercontent.com/35125132/56723976-a4343000-677c-11e9-9641-7cddf0aaff83.png)

**Comment by jyy1990** [comment]
@SoftwareKing  这个画圈的微服务我照着你博客那个说明，在pom里添加了依赖和配置，yml里也添加了，我现在想在mossweb页面上看到这个微服务，求助大佬啊，谢谢
![image](https://user-images.githubusercontent.com/35125132/56724127-f7a67e00-677c-11e9-9b44-5faa8d6d442f.png)

**Comment by innerpeacez** [comment]
@jyy1990  http://localhost:2111/eureka

**Comment by SoftwareKing** [comment]
注册中心的地址填错了,是这个http://localhost:2111/eureka，楼上正解 @jyy1990

**Comment by jyy1990** [comment]
@SoftwareKing  @innerpeacez  感谢2位，改了，可是没有任何变化呀
![image](https://user-images.githubusercontent.com/35125132/56777267-17808500-6803-11e9-9244-f939018672ae.png)
![image](https://user-images.githubusercontent.com/35125132/56777291-41d24280-6803-11e9-83ab-dcd216dd183a.png)

**Comment by jyy1990** [comment]
@SoftwareKing  @innerpeacez 非常感谢2位，解决问题了，是因为我的eureka设置了密码，添加注册中心的时候URL里面忘记写密码了！！！

**Comment by jyy1990** [comment]
这里给其他小朋友警醒，我添加注册中心填的URL一开始我一直以为是eureka的访问地址，如图：
![image](https://user-images.githubusercontent.com/35125132/56780141-b3fd5400-6810-11e9-84f5-cc94e8c370a6.png)
后来二位老哥提醒，我发现原来是填注册到eureka的地址，如果eureka有设置密码的话应该是这样：
http://root:123456@localhost:2111/eureka/

**Comment by SoftwareKing** [comment]
@jyy1990 解决了就好，加我微信Software_King，我拉你进微信吧，交流方便一些。

**Comment by jyy1990** [comment]
@SoftwareKing 昨天加了，谢谢
