### ISSUE TITLE
应用点击提示未被接管

### ISSUE THREAD

**Issue by zhx19940113** [SpringCloud/Moss#20]
应用点击提示未被接管

**Comment by innerpeacez** [comment]
@zhx19940113 
大佬好像还没有开发，页面接管的功能，现在好像还需要手动添加一条数据
![image](https://user-images.githubusercontent.com/37059529/56857148-ab398900-699c-11e9-973b-35fab5c6444a.png)

**Comment by SoftwareKing** [comment]
@zhx19940113 五一之后，增加应用功能开发好

**Comment by homeant** [comment]
添加功能已经完成
