### ISSUE TITLE
应用接入后没有数据

### ISSUE THREAD

**Issue by zhx19940113** [SpringCloud/Moss#22]
![image](https://user-images.githubusercontent.com/6321342/56858581-d4fbab80-69ae-11e9-89ce-ff99f484e77f.png)

**Comment by zhx19940113** [comment]
![image](https://user-images.githubusercontent.com/6321342/56858605-7daa0b00-69af-11e9-80f3-13339d351de9.png)
![image](https://user-images.githubusercontent.com/6321342/56858611-8d295400-69af-11e9-8b75-4724713289ac.png)
application_name和take_over也配置了。

**Comment by jyy1990** [comment]
配置完应用是up状态吗？如果是up状态的话，有配置skywalking吗？

**Comment by SoftwareKing** [comment]
@zhx19940113 详细问题进钉钉群
