### ISSUE TITLE
微服务配置client2.x启动后，控制台每隔几秒空指针/actuator/metricsInfo

### ISSUE THREAD

**Issue by jyy1990** [SpringCloud/Moss#28]
/actuator/metricsInfo
![image](https://user-images.githubusercontent.com/35125132/56942182-ce566b00-6b4b-11e9-9582-2963ea2c03e0.png)

**Comment by homeant** [comment]
已经调整，见
c3af284976943f5abe584efaf93031e16dd51aeb
