### ISSUE TITLE
客户端按照要求配置完，服务端看不到服务的信息

### ISSUE THREAD

**Issue by zzzxdm** [SpringCloud/Moss#47]
Moss服务端只能看到haol-moss这一个服务，其他的监控不到啊。
1、增加依赖
2、application.yml配置groupId
3、pom增加plugin
这些都按照文档做了，应用启动完毕，Moss控制台看不到啊

**Comment by SoftwareKing** [comment]
@zzzxdm 加钉钉群，有视频使用教程
