### ISSUE TITLE
建议整理一份部署文档

### ISSUE THREAD

**Issue by Neil-Zhou** [SpringCloud/Moss#56]
要是有一份部署文档就好了。所以建议出具一份部署文档，这样就可以快速使用和集成。不过挺赞的。这个系统看起来非常nice！

**Comment by houshihao** [comment]
部署文档缺失~~~~

**Comment by SoftwareKing** [comment]
@Neil-Zhou @houshihao 欢迎进钉钉群交流

**Comment by mars05** [comment]
@SoftwareKing 钉钉群失效了

**Comment by TrumanDu** [comment]
文档缺失，分页指定大小无用

**Comment by SoftwareKing** [comment]
有问题可以加我微信Software_King
