### ISSUE TITLE
已经严格按照视频部署MOSS服务端和客户端了但是依然显示服务状态为DOWN

### ISSUE THREAD

**Issue by JunZhou2016** [SpringCloud/Moss#57]
已经严格按照视频教程部署MOSS服务端和客户端了但是依然显示服务状态为DOWN，非常感谢您的开源，但是建议添加部署操作文档，谢谢。
     PS:源码为Release版本的。

**Comment by SoftwareKing** [comment]
@JunZhou2016 已经解决了，支持容器化之后，本地运行开随机端口，Eureka不支持
